ALTER TYPE "Role" RENAME TO "Role_old";

CREATE TYPE "Role" AS ENUM ('ORDERING', 'RECEIVING', 'DELIVERY');

ALTER TABLE "User"
  ALTER COLUMN "role" DROP DEFAULT,
  ALTER COLUMN "role" TYPE "Role"
  USING (
    CASE "role"::text
      WHEN 'ADMIN' THEN 'ORDERING'
      WHEN 'MANAGER' THEN 'ORDERING'
      WHEN 'PPIC' THEN 'RECEIVING'
      WHEN 'USER' THEN 'DELIVERY'
    END
  )::"Role",
  ALTER COLUMN "role" SET DEFAULT 'ORDERING';

DROP TYPE "Role_old";
